#version 460

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0) uniform sampler2D occluderTex;
layout(binding = 1, rg32f) uniform writeonly image2D seedTex;

uniform ivec2 resolution;

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);

    if (pixel.x >= resolution.x || pixel.y >= resolution.y)
    return;

    vec2 uv = (vec2(pixel) + 0.5) / vec2(resolution);

    float occ = texture(occluderTex, uv).r;

    if (occ > 0.5) {
        imageStore(seedTex, pixel, vec4(uv, 0, 0));
    } else {
        imageStore(seedTex, pixel, vec4(-1.0, -1.0, 0, 0));
    }
}